- name: variables from arguments
  hosts: localhost
  tasks:
  - name: get from args
    ansible.builtin.debug:
      msg: "Hello {{PERSON}}, Good {{WISHES}}"
  

  #anible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 <playbook-name> -e PERSON=SIVA -e WISHES=morning-from-prompt